### ISSUE TITLE
Error: Navigation Timeout Exceeded: 30000ms exceeded

### ISSUE THREAD

**Issue by gcazaciuc** [tsuyoshiwada/storybook-chrome-screenshot#1]
I'm trying to ran the tool against a storybook setup. Admitely the server takes a while to start up because it is ran in a monorepo of multiple components, compiles things with typescript, uses babel and also runs TSLint.

When the initialization gets to 'Fetching the target components...' it fails with the above error of 'Error: Navigation Timeout Exceeded: 30000ms exceeded'.

Any suggestions on how to debug this ? Or maybe the timout should be specified as a CLI param ?

**Comment by gcazaciuc** [comment]
Additionally , it seems the underlying process isn't properly cleaned up when an unexpected error such as this is encountered. I can see a node process for storybook still running which makes subsequent runs get stuck at 'Launching storybook server' phase.

**Comment by tsuyoshiwada** [comment]
Hi @gcazaciuc, Thanks for Issues!
I am very useful information because I have not been able to try it with a big project yet.

I would like to add a parameter like `--browser-timeout <ms>`.

`storybook-chrome-screenshot` does not have an implementation yet to do debugging.
It is possible to emulate client behavior by accessing `http://localhost:9001?full=1&chrome-screenshot=1` as workaround.

We are considering adding the `--debug` option in the next version.

**Comment by tsuyoshiwada** [comment]
Hi @gcazaciuc.
Release version 0.2.0 which supports `--browser-timeout` options.
Please check when you have time.

**Comment by gcazaciuc** [comment]
I've increased the browser timeout and now it works, it manages to process all of the stories. However, I'm not entirely sure why such a timeout is needed in the first place. My concern is that on other machines the increased timeout might not be enough while on others it might be too high. 

Anyhow, just wanted to say thanks and let you know that with increased timeout it works now!

**Comment by tsuyoshiwada** [comment]
@gcazaciuc Thank you for confirmation!

You're right.
We will soon add the `--debug` option.
I am very happy if you can test it with the project you are working on at that time :smiley:

May I close this Issues?

**Comment by gcazaciuc** [comment]
Thanks so much. I believe we can close this one.

**Comment by tsuyoshiwada** [comment]
@gcazaciuc Thank you too :smile: !
