### ISSUE TITLE
Move examples in the separated repos and configure CI with visual regression testing 

### ISSUE THREAD

**Issue by alexeybondarenko** [tsuyoshiwada/storybook-chrome-screenshot#27]
This change can help new users to see full configuration process. We can use Travis CI + Argos CI for the examples.

**Comment by Quramy** [comment]
I agree that make example repositories to help users who want full configuration (the `examples` dir in this repo is used for e2e testing, so it's better to keep this ) .

I've created https://github.com/Quramy/angular-sss-demo, which includes : 

- Docker based CI
- Visual Regression Testing using [reg-suit](https://reg-viz.github.io/reg-suit/)

@tsuyoshiwada put a link to this repo onto README if you never mind ?

**Comment by tsuyoshiwada** [comment]
@alexeybondarenko Thank you for Issues! And sorry for the late reply... :sob:
@Quramy spoke for us. Because examples are subject to the e2e test, I would like to keep it as it is.

---

@Quramy 
Of course, adding a link is greatly appreciated!
I would like a section like Examples or Links :smiley:

**Comment by alexeybondarenko** [comment]
@tsuyoshiwada we can add them to this repo as submodules 😄

**Comment by tsuyoshiwada** [comment]
@Quramy I added an examples section to the document, And posted angular-sss-demo! Thanks :smiley:

**Comment by tsuyoshiwada** [comment]
@alexeybondarenko I do not feel the need for it myself yet, so I would like to keep it as it is this time.
I am sorry I did not meet expectations :cry:

**Comment by oliviertassinari** [comment]
@alexeybondarenko Regarding Argos-CI, we host different integration examples on the main repository: https://github.com/argos-ci/argos/tree/master/examples. We even have an example with storybook. However, I think that we could be documenting storybook-chrome-screenshot too. I have created an issue about it: https://github.com/argos-ci/argos/issues/347.

**Comment by oliviertassinari** [comment]
@alexeybondarenko It's hard for me to get feedback from our users on Argos-CI. I believe you have been a user. Anything pain point to share or topic you would want us to work on?
