### ISSUE TITLE
Provide a way to decorate all stories in a file or all available stories

### ISSUE THREAD

**Issue by gcazaciuc** [tsuyoshiwada/storybook-chrome-screenshot#3]
I'm trying to use the `addDecorator` API to decorate all stories in a certain file, something along these lines:
```js
storiesOf('sticky-button', module)
    .addDecorator(withReadme(README))
    .addDecorator(checkA11y)
    .addDecorator(withScreenshot())
    .add('Basic Sticky Button', () => (
        <StickyButton label={label} disabled={false} onClick={action(`click`)} />))
    .add('Basic Disabled Sticky Button', () => (
        <StickyButton label={label} disabled={true} onClick={action(`click`)} />))
```

I would  like to take screenshots of both of the stories without having to decorate them manually.
The Storybook build succeeds however when i try to take screenshots it gets stuck indefinetely at ''Fetching the target components" .

Also, it would be really usefull if one could take screenshots of all stories available without the need to decorate each and every one with `withScreenshot`.

**Comment by tsuyoshiwada** [comment]
Hi @gcazaciuc, That makes sense.
I will try to correspond with the next version :+1:

**Comment by tsuyoshiwada** [comment]
Hi @gcazaciuc.
Release version 0.4.0 which supports `addDecorator`.
Please check when you have time :smiley:

**Comment by gcazaciuc** [comment]
It works really nice, thanks for the hard work and effort you've put into this. The only case where i found it didn't work is when the stories were generated dynamically:

Below code doesn't work:

```js
Utils.devices({ position: 'relative' }).forEach(device =>
    (storiesOf('sticky-button', module))
        .addDecorator(withReadme(README))
        .addDecorator(checkA11y)
        .addDecorator(withCode(style, 'sass'))
        .addDecorator(withScreenshot())
        .add(`StickyCart for  ${device.deviceName}`, () => (
            Utils.CombinationRenderer(StickyButton, props, device.style)
        )));
```

Below code does work:

```js
Utils.devices({ position: 'relative' }).forEach(device =>
    (storiesOf('sticky-button', module))
        .addDecorator(withReadme(README))
        .addDecorator(checkA11y)
        .addDecorator(withCode(style, 'sass'))
        .add(`StickyCart for  ${device.deviceName}`, withScreenshot()(() => (
            Utils.CombinationRenderer(StickyButton, props, device.style)
        ))));
```

Notice in the working example that the dynamically generated story is wrapped in a `withScreenshot` call as opposed in setting a decorator.

It's not a big deal and i believe we can live without it if it's hard to fix. The normal stories work just fine using `addDecorator`

**Comment by tsuyoshiwada** [comment]
@gcazaciuc Thanks for confirmation!
Since it does not seem to be a big problem, I would like to prioritize implementation of new functions :+1:
