### ISSUE TITLE
Failing runnning with Docker

### ISSUE THREAD

**Issue by diegolamanno** [tsuyoshiwada/storybook-chrome-screenshot#32]
I had **storybook-chrome-screenshot** with **reg-viz** working on CircleCi without any problems. After updating from `0.10.0` to `1.0.0` it stopped working while _trying to mount storybook_. I coulnd't figured out what's causing the problem.

It breaks running on Docker (either locally or in Circle). I am using the recommended setup to run Puppeteer on Docker https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker

Here are the logs when I run it with `--debug`
```
yarn run v1.3.2
warning ../../../package.json: No license field
$ storybook-chrome-screenshot -p 9009 -c .storybook --debug
 DEBUG  [CLI Options] { port: '9009',
  host: 'localhost',
  staticDir: undefined,
  configDir: '.storybook',
  outputDir: '__screenshots__',
  filterKind: undefined,
  filterStory: undefined,
  browserTimeout: 30000,
  parallel: 4,
  injectFiles: [],
  silent: false,
  debug: true,
  ciMode: true,
  cwd: '/home/pptruser/website',
  cmd: '/home/pptruser/website/node_modules/.bin/start-storybook' }

 LAUNCH  Launching storybook server ...

 DEBUG  [Command Arguments] -p 9009 -c .storybook -h localhost
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

This is running using:
- Node 8.9.4
- yarn 1.3.2
- npm 5.6.0

**Comment by baires** [comment]
You may want to check the docker logs (npm logs) but my guess is that puppeteer is not configurated properly. The docker image from `regviz/node-xcb` seems to do the trick to get puppeteer up and running.

But right now Im facing another problem. There is a Unhandled promise rejection.

```
 CAPTURE  Capturing component screenshots ...

📷  [=                                       ] 2/64(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Page crashed!
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Page crashed!
```

Anyone else running this package with Docker?

**Comment by tsuyoshiwada** [comment]
@diegolamanno The following link will be of your help :dog:

https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
