### ISSUE TITLE
[Feature proposal] Provide a way to filter stories by regex

### ISSUE THREAD

**Issue by gcazaciuc** [tsuyoshiwada/storybook-chrome-screenshot#4]
Sometimes you want to run just a subset of the tests in order to debug an issue or just because you would like to run the tests very quickly locally for the area affected by changes.
In a similar manner, Storyshots( https://github.com/storybooks/storybook/tree/master/addons/storyshots ) permits in using a regex to filter out tests by either name or story( eg  storyNameRegex:  /buttons/).

It would be really cool if the same could be done in storybook-chrome-screenshot by using a CLI param.

**Comment by tsuyoshiwada** [comment]
Hi @gcazaciuc, Thank you for a great proposal :+1:
For example, what do you think about specifying the parameters as follows?

```bash
$ storybook-chrome-screenshot --filter-kind "/Button/" --filter-story "/with\s.+/"
```

Filter `kind` and` story` respectively.

**Comment by gcazaciuc** [comment]
I really like that, looks great!

**Comment by tsuyoshiwada** [comment]
@gcazaciuc Thx! I would like to implement it in the next release :smile:

**Comment by tsuyoshiwada** [comment]
@gcazaciuc. Released as `0.5.0-alpha.1` :+1:

If there is no problem with the behavior, I'd like to release the version which removed `alpha`.
Please check when you have time.

**Comment by gcazaciuc** [comment]
Hi. Thanks, it also works just fine!

**Comment by tsuyoshiwada** [comment]
Release as `0.5.0` :tada:
