### ISSUE TITLE
Custom screenshot file name

### ISSUE THREAD

**Issue by theKashey** [tsuyoshiwada/storybook-chrome-screenshot#42]
I would like to have customizable `story2filename`, to land target images, for example, next to .story file, not all in one directory.

**Comment by theKashey** [comment]
So - storybook provides a fileName in context for each story (currently broken in storybook4), and one could use it to generate a file name.
My proposal - let the user specify where to put a file, the only concert - how.
There are 2 possibilities - a function, or a pattern. 

Pattern is a bit more common approach, and allow you do to a lot, but most complex cases are undoable. Meanwhile, function is much harder to use.

Pattern could look like
```js
const DEFAULT_FILE_PATTERN = '{kind}-{story}{knobs}{ns}{vp}';
export const story2filename = (params: Story2FilenameParams) => {
  const ns = params.namespace ? `_${params.namespace}` : '';
  const vp = params.viewport ? `-${viewport2string(params.viewport)}` : '';
  const knobs = params.knobs ? `-${knobs2string(params.knobs)}` : '';

  const replacements = {
    kind: params.kind,
    story:params.story,
    knobs,
    ns,
    vp
  };

  const filename =
    (params.filePattern || DEFAULT_FILE_PATTERN)
     .replace(/\{\w+\}/g, key => replacements[key])

  return `${filenamify(filename)}.png`;
};
```

It could be useful, but it will not solve my task - place a storyshots next to storyfile, while function could. 

Any thoughts?

**Comment by tsuyoshiwada** [comment]
I agree with the generation of file names using patterns :+1:

> for example, next to .story file, not all in one directory.

In order to satisfy your task, you need to know the file path of each story.
But regarding that I have no correct answer ... :sob:

Hmm...

**Comment by theKashey** [comment]
You could have it, it is a part of storyContext. see https://github.com/theKashey/storybook/blob/bdc9bed648a3316ece83764cbf8e800c0b4d6fc3/lib/core/src/client/preview/client_api.js#L91

If you like patterns - I could open a PR, it's ready already. I just found that I have no filename, and first have to fix storybook(v4).

**Comment by theKashey** [comment]
@tsuyoshiwada - done, but it is not complete - I dont touch CLI interface, and still looking forward to access fileName somehow.

**Comment by andre-brdoch** [comment]
Is this still possible nowadays? I had a look and couldn't find the `filePattern` option anymore 😃
