### ISSUE TITLE
By default aplha version gets installed

### ISSUE THREAD

**Issue by krzkaczor** [tsuyoshiwada/storybook-chrome-screenshot#45]
When I run `yarn add storybook-chrome-screenshot` or `npm install storybook-chrome-screenshot` by default new alpha version (`1.1.0-alpha.1`) gets installed which doesnt work correctly. Falling back to `1.0.1` solved my problems.

I think you should [tag](https://www.npmjs.com/package/tag-release) dev releases appropriately. 

Anyways, great work :)

**Comment by tsuyoshiwada** [comment]
Hi @krzkaczor, Thank you for report :heart:

We will tag you properly from the next version :+1:
Thx!

**Comment by tsuyoshiwada** [comment]
I'd like to keep this Issue open for a while :hand:

**Comment by tsuyoshiwada** [comment]
@krzkaczor 

Since the `alpha` version disappears, this Issue closes.

Next, when tagging with `alpha` version, tag is appended appropriately!
Thank you!
