### ISSUE TITLE
Output any kind of debug info to the output

### ISSUE THREAD

**Issue by markelog** [tsuyoshiwada/storybook-chrome-screenshot#47]
Did the installation path, added one `withScreenshot()` for  testing to a relatively big size (I think) storybook.

After the 
`$ ./node_modules/.bin/storybook-chrome-screenshot -p 9001 -c .storybook`

I get 
```
 LAUNCH  Launching storybook server ...
 PREPARE  Fetching the target components ...
```
And nothing else.

localhost:9001 shows me the storybook normal build version, no errors, shows element with `withScreenshot` as well.

Would want to debug it, but it seems futile without any kind of logs, the suggestions or something from the tool would be helpful

**Comment by markelog** [comment]
After 20 minutes it unfrozed, yey! But issues still stands though.

Also it seems performing significantly slower then @storybook/addons-storyshots (newer version can do screenshots). Have you considered any performance improvements, it's a bit off-topic I know? Should I create an issue about it?

**Comment by tsuyoshiwada** [comment]
Hi @markelog, Thank you for Issues :smiley:

I'm also aware of performance problems... :innocent:
However, we are still struggling to improve now.

By the way, when debugging, use the `--debug` flag to get the output.

**Comment by tsuyoshiwada** [comment]
By PR #50, the performance of CAPTURE phase has improved :+1:
Performance improvement will be done little by little in the future.

---

I think that the content of the title has been solved, so may I close this Issue :smiley: ??

**Comment by markelog** [comment]
Sounds good, looking forward to testing it :)
