### ISSUE TITLE
[feature request] Compare Screenshots

### ISSUE THREAD

**Issue by adamchenwei** [tsuyoshiwada/storybook-chrome-screenshot#48]
will we allow screenshot comparison with to-be-generated version for edited components?

Thanks!

**Comment by Quramy** [comment]
@adamchenwei Check https://github.com/tsuyoshiwada/scs-with-reg-viz out. It's a sample repo using storybook-chrome-screenshot and reg-suit 😄 .

**Comment by tsuyoshiwada** [comment]
It's recommended that you use tools such as `reg-suit`.
Therefore I think I will close this Issue. Thanks :+1:
