### ISSUE TITLE
npm install warning for @types/commander

### ISSUE THREAD

**Issue by osdevisnot** [tsuyoshiwada/storybook-chrome-screenshot#51]
We probably don't need @types/commander as dependency based on this warning:

![image](https://user-images.githubusercontent.com/802242/40741578-becdbe98-6400-11e8-9bf9-7bbe2bb83c94.png)

**Comment by tsuyoshiwada** [comment]
Hi @osdevisnot, Thank you for report :pray: 

I will fix this problem in the next release.
Thanks :heart:

**Comment by tsuyoshiwada** [comment]
We solved this problem and will close it :+1:
