### ISSUE TITLE
[Feature] Improve performance by parallelizing component screenshot

### ISSUE THREAD

**Issue by gcazaciuc** [tsuyoshiwada/storybook-chrome-screenshot#7]
The tool is just awesome. I'm testing it on a large repo. Currently I've setup only 35 stories to be screenshot-ed( I have several hundred per total).

For 35 stories it takes around 150 seconds to execute.

I wonder if we can parallelize taking screenshots(maybe in multiple child process) and/or finding the components to screenshot so the tests can run more efficient even if the number of stories is increased.

Please let me know your thoughts on this.

**Comment by tsuyoshiwada** [comment]
Hi @gcazaciuc, Thank you for awesome proposal :+1:

Although it is necessary to verify whether to increase the page of child process or puppeteer, I will try implementing it.

**Comment by tsuyoshiwada** [comment]
@gcazaciuc Alpha version has been released.

When shooting screenshots, we started up pages side-by-side to increase speed.
However, it did not become as fast as I expected... :cry:

As a result of verifying with the story of 10, the average result is about 6% faster as shown below.

```
# v0.5.0
Time: 14,597ms
Time: 14,535ms
Time: 14,614ms

# 0.6.0-alpha.1 (--parallel 4)
Time: 13,456ms
Time: 13,674ms
Time: 13,656ms
```

Please check when you have time.

---

If you do not expect to be faster than you thought by this measure, I would like to consider how to start multiple child_process.
