### ISSUE TITLE
[Feature proposal] Ability to disable animations via options

### ISSUE THREAD

**Issue by gcazaciuc** [tsuyoshiwada/storybook-chrome-screenshot#8]
Animations tend to make screenshot testing difficult due to the fact that they make the screenshots non-deteministic.
Some existing tools have the ability to turn off the animations exactly for this reason( eg https://github.com/Huddle/PhantomCSS/blob/master/phantomcss.js ).
Maybe we could have an option that can control this behaviour. In PhantomCSS the process of disabling the animations is something similar to:
```js
function disableAnimations() {
			var jQuery = window.jQuery;
			if ( jQuery ) {
				jQuery.fx.off = true;
			}

			var css = document.createElement( "style" );
			css.type = "text/css";
			css.innerHTML = "* { -webkit-transition: none !important; transition: none !important; -webkit-animation: none !important; animation: none !important; }";
			document.body.appendChild( css );
		}

		if ( document.readyState !== "loading" ) {
			disableAnimations();
		} else {
			window.addEventListener( 'load', disableAnimations, false );
		}
```

**Comment by tsuyoshiwada** [comment]
Hi @gcazaciuc, Thank you for Issues.

For example, what do you think is there a CLI option to inject scripts when accessed by Puppeteer :smiley: ?

```bash
$ storybook-chrome-screenshot --inject-script ./path/to/script.js
```

In this case, in addition to invalidating animation, we can also do other work, so we think that it is advantageous to have high versatility.

**Comment by gcazaciuc** [comment]
Yes, that's probably even better! :) We can cover many more cases that way.

**Comment by tsuyoshiwada** [comment]
Hi @gcazaciuc, Thanks for confirmation!
I would like to implement it in the next release :+1:

**Comment by tsuyoshiwada** [comment]
@gcazaciuc. Released as `0.6.0` :+1:
Please check when you have time.

**Comment by willisplummer** [comment]
It looks like this issue can be closed

**Comment by tsuyoshiwada** [comment]
@willisplummer Thanks!
