### ISSUE TITLE
Distribute sourcemaps with npm package?

### ISSUE THREAD

**Issue by breathe** [tsuyoshiwada/storybook-chrome-screenshot#9]
Would it be possible to distribute sourcemaps with the npm package?

I'm hitting a bug whereby after running screenshot I see:

``` LAUNCH  Launching storybook server... ⠴```

And it hangs forever.  Trying to debug in vscode debugger but its pretty painful to step through the compiled output without sourcemaps ...

**Comment by tsuyoshiwada** [comment]
Hi @breathe, Thanks for Issues.
I would like to add sourcemaps to the next version :+1:

Meanwhile, the `--debug` option of the `storybook-chrome-screenshot` command may be helpful.

**Comment by tsuyoshiwada** [comment]
@breathe Released as `0.6.0` :tada:
Please check when you have time.

**Comment by breathe** [comment]
Great the sourcemaps work for me while debugging!  :)  Its a little strange to actually set breakpoints in the module as the vscode code navigator view (at edit time) only exposes the files on disk -- but at debug time having the maps is great.

<img width="793" alt="screen shot 2017-09-30 at 3 39 57 pm" src="https://user-images.githubusercontent.com/434034/31049712-b1969048-a5f5-11e7-865a-0ba87cc111f5.png">

I opened a bug with vscode to see if they could add a feature to support an 'edit time' interpretation of source maps -- to allow npm projects that distribute compiled.js and compiled.map to work out of the box in the nicest way with debugging

https://github.com/Microsoft/vscode/issues/35439
